"""
URL routing for Knowledge Base API endpoints.
"""
from django.urls import path
from . import views

app_name = 'knowledge'

urlpatterns = [
    path(
        'workspace/<str:workspace_id>/knowledge',
        views.KnowledgeListView.as_view(),
        name='knowledge-list'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>',
        views.KnowledgeDetailView.as_view(),
        name='knowledge-detail'
    ),
    path(
        'workspace/<str:workspace_id>/folders',
        views.KnowledgeFolderListView.as_view(),
        name='folder-list'
    ),
    path(
        'workspace/<str:workspace_id>/folders/<str:folder_id>',
        views.KnowledgeFolderDetailView.as_view(),
        name='folder-detail'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/document',
        views.DocumentListView.as_view(),
        name='document-list'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/document/<uuid:document_id>',
        views.DocumentDetailView.as_view(),
        name='document-detail'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/document/<uuid:document_id>/paragraph',
        views.ParagraphListView.as_view(),
        name='paragraph-list'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/document/<uuid:document_id>/paragraph/<uuid:paragraph_id>',
        views.ParagraphDetailView.as_view(),
        name='paragraph-detail'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/problem',
        views.ProblemListView.as_view(),
        name='problem-list'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/problem/<uuid:problem_id>',
        views.ProblemDetailView.as_view(),
        name='problem-detail'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/problem/<uuid:problem_id>/mapping',
        views.ProblemParagraphMappingListView.as_view(),
        name='problem-mapping-list'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/problem/<uuid:problem_id>/mapping/<uuid:mapping_id>',
        views.ProblemParagraphMappingDetailView.as_view(),
        name='problem-mapping-detail'
    ),
    # Tag endpoints
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/tag',
        views.TagListView.as_view(),
        name='tag-list'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/tag/<uuid:tag_id>',
        views.TagDetailView.as_view(),
        name='tag-detail'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/tag/keys',
        views.TagKeysView.as_view(),
        name='tag-keys'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/tag/key/<str:key>/values',
        views.TagValuesView.as_view(),
        name='tag-values'
    ),
    # Document tag endpoints
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/document/<uuid:document_id>/tag',
        views.DocumentTagListView.as_view(),
        name='document-tag-list'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/document/<uuid:document_id>/tag/<uuid:tag_id>',
        views.DocumentTagDetailView.as_view(),
        name='document-tag-detail'
    ),
    path(
        'workspace/<str:workspace_id>/knowledge/<uuid:knowledge_id>/documents-by-tag',
        views.DocumentsByTagView.as_view(),
        name='documents-by-tag'
    ),
]
